MOR-321: Updated workflow to add buttons to the bar
oregondesignservices/MorphicCommunity pull request #36
Opened 2020-09-25 18:03 UTC by javihernandez

See https://morphic.atlassian.net/browse/MOR-321

2020-09-28 09:02 UTC, kaspermarkus requested changes

2020-09-28 09:02 UTC, kaspermarkus commented on src/components/dashboard/PreviewItem.vue
> +    }
hmm... looking like I can't comment on random lines in your pull, so I'll put the other part here...

So in MorphicBarEditor.vue, you modify line 271 and 278 (the two 'simplified' representations of the buttons in the green area) to listen to the event:

```
<PreviewItem :item="button" :simplified="true" :noImage="true" class="noImage" @myEvent='dropToBar({data: $event') />
```

or something along those lines

2020-09-28 14:33 UTC, javihernandez commented
@kaspermarkus ok, I've updated it to use an event following your advice. ready again for review ;)

2020-09-29 13:06 UTC, kaspermarkus approved these changes
Awesome! Thanks Javi

2020-09-29 13:07 UTC, merged